spring:
  application:
    name: portfolio-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: atuyishime28@gmail.com
    password: YOUR_APP_PASSWORD_HERE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080